const data = {
    products: [
        {
            name: 'Nike Slim Shirt',
            slug: 'nike-slim-shirt',
            category: 'Shirt',
            image: '../public/img/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality shirt',
        },
        {
            name: 'Adidas Fit Shirt',
            slug: 'adidas-fit-shirt',
            category: 'Shirt',
            image: '../public/img/p2.jpg',
            price: 250,
            countInStock: 20,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality shirt',
        },
        {
            name: 'Nike Slim Pant',
            slug: 'nike-slim-pant',
            category: 'Shirt',
            image: '../public/img/p3.jpg',
            price: 25,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'High Quality shirt',
        },
        {
            name: 'Adidas Fit Pans',
            slug: 'adidas-fit-pans',
            category: 'Pans',
            image: '../public/img/p4.jpg',
            price: 65,
            countInStock: 20,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality shirt',
        },
    ],
};